apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
spec:
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secret.name }}
  refreshInterval: {{ .Values.secret.refresh_interval }}
  data:
    - secretKey: {{ .Values.secret.name }}
      remoteRef:
        key: {{ .Values.secret.key }}